-- =====================================================
-- OEM EV WARRANTY MANAGEMENT SYSTEM - V1 Initial Database Schema & Seed Data
-- =====================================================

-- Trigger function for updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =====================================================
-- 1. ROLES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_roles_updated_at ON roles;
CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON roles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 2. USERS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(20),
    service_center VARCHAR(100),
    active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 3. USER_ROLES JOIN TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- =====================================================
-- 4. CUSTOMERS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(20),
    address VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    country VARCHAR(100),
    id_number VARCHAR(50),
    id_type VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;
CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 5. VEHICLES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin VARCHAR(17) NOT NULL UNIQUE,
    model VARCHAR(100),
    make VARCHAR(100),
    year INT,
    color VARCHAR(50),
    battery_type VARCHAR(100),
    battery_capacity DOUBLE PRECISION,
    motor_type VARCHAR(100),
    mileage INT DEFAULT 0,
    manufacture_date DATE,
    purchase_date DATE,
    registration_date DATE,
    warranty_start_date DATE,
    warranty_end_date DATE,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    customer_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);

DROP TRIGGER IF EXISTS trg_vehicles_updated_at ON vehicles;
CREATE TRIGGER trg_vehicles_updated_at BEFORE UPDATE ON vehicles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 6. PARTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(50),
    price DECIMAL(15, 2),
    warranty_months INT DEFAULT 12,
    manufacturer VARCHAR(255),
    model_compatibility VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    min_stock_level INT DEFAULT 5,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_parts_updated_at ON parts;
CREATE TRIGGER trg_parts_updated_at BEFORE UPDATE ON parts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 7. VEHICLE_PARTS TABLE (Installed Parts)
-- =====================================================
CREATE TABLE IF NOT EXISTS vehicle_parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    part_id BIGINT NOT NULL,
    serial_number VARCHAR(100),
    installation_date DATE,
    warranty_start_date DATE,
    warranty_end_date DATE,
    status VARCHAR(20) DEFAULT 'INSTALLED',
    notes TEXT,
    installed_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    FOREIGN KEY (part_id) REFERENCES parts(id),
    FOREIGN KEY (installed_by) REFERENCES users(id)
);

DROP TRIGGER IF EXISTS trg_vehicle_parts_updated_at ON vehicle_parts;
CREATE TRIGGER trg_vehicle_parts_updated_at BEFORE UPDATE ON vehicle_parts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 8. WARRANTY_POLICIES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS warranty_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    duration_months INT NOT NULL,
    mileage_limit INT,
    coverage_type VARCHAR(50),
    deductible DECIMAL(10, 2),
    applicable_models VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_warranty_policies_updated_at ON warranty_policies;
CREATE TRIGGER trg_warranty_policies_updated_at BEFORE UPDATE ON warranty_policies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 9. WARRANTY_CLAIMS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS warranty_claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number VARCHAR(50) NOT NULL UNIQUE,
    vehicle_id BIGINT NOT NULL,
    vehicle_part_id BIGINT,
    warranty_policy_id BIGINT,
    failure_description TEXT,
    diagnosis_notes TEXT,
    repair_description TEXT,
    labor_hours DOUBLE PRECISION,
    labor_cost DECIMAL(15, 2),
    parts_cost DECIMAL(15, 2),
    total_cost DECIMAL(15, 2),
    status VARCHAR(30) DEFAULT 'DRAFT',
    mileage_at_claim INT,
    submitted_by BIGINT,
    technician_id BIGINT,
    reviewed_by BIGINT,
    service_center VARCHAR(100),
    rejection_reason TEXT,
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    FOREIGN KEY (vehicle_part_id) REFERENCES vehicle_parts(id),
    FOREIGN KEY (warranty_policy_id) REFERENCES warranty_policies(id),
    FOREIGN KEY (submitted_by) REFERENCES users(id),
    FOREIGN KEY (technician_id) REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

DROP TRIGGER IF EXISTS trg_warranty_claims_updated_at ON warranty_claims;
CREATE TRIGGER trg_warranty_claims_updated_at BEFORE UPDATE ON warranty_claims FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 10. CLAIM_ATTACHMENTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS claim_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(100),
    file_size BIGINT,
    uploaded_by BIGINT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (claim_id) REFERENCES warranty_claims(id) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

-- =====================================================
-- 11. SERVICE_CAMPAIGNS TABLE (Recalls & Bulletins)
-- =====================================================
CREATE TABLE IF NOT EXISTS service_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_number VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    campaign_type VARCHAR(50),
    status VARCHAR(20) DEFAULT 'DRAFT',
    severity_level VARCHAR(20) DEFAULT 'MEDIUM',
    affected_models VARCHAR(500),
    remedy_description TEXT,
    estimated_repair_time DOUBLE PRECISION,
    total_affected INT DEFAULT 0,
    completed_count INT DEFAULT 0,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_service_campaigns_updated_at ON service_campaigns;
CREATE TRIGGER trg_service_campaigns_updated_at BEFORE UPDATE ON service_campaigns FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 12. INVENTORY TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL,
    service_center VARCHAR(100) NOT NULL,
    quantity_on_hand INT DEFAULT 0,
    quantity_reserved INT DEFAULT 0,
    quantity_on_order INT DEFAULT 0,
    reorder_point INT DEFAULT 5,
    location VARCHAR(100),
    last_restock_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (part_id) REFERENCES parts(id),
    UNIQUE (part_id, service_center)
);

DROP TRIGGER IF EXISTS trg_inventory_updated_at ON inventory;
CREATE TRIGGER trg_inventory_updated_at BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 13. SERVICE_HISTORY TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS service_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    service_type VARCHAR(100),
    description TEXT,
    mileage_at_service INT,
    service_date TIMESTAMP,
    completion_date TIMESTAMP,
    service_center VARCHAR(100),
    technician_id BIGINT,
    warranty_claim_id BIGINT,
    service_campaign_id BIGINT,
    labor_hours DOUBLE PRECISION,
    cost DECIMAL(15, 2),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    FOREIGN KEY (technician_id) REFERENCES users(id),
    FOREIGN KEY (warranty_claim_id) REFERENCES warranty_claims(id),
    FOREIGN KEY (service_campaign_id) REFERENCES service_campaigns(id)
);

-- =====================================================
-- 14. AUDIT_LOGS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id BIGINT,
    details TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 15. APPOINTMENTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    campaign_id BIGINT,
    appointment_date TIMESTAMP NOT NULL,
    status VARCHAR(20) DEFAULT 'SCHEDULED',
    service_center VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    FOREIGN KEY (campaign_id) REFERENCES service_campaigns(id)
);

-- =====================================================
-- 16. PART_ALLOCATIONS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS part_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL,
    service_center VARCHAR(100) NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    tracking_number VARCHAR(50),
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    shipped_at TIMESTAMP NULL,
    received_at TIMESTAMP NULL,
    FOREIGN KEY (part_id) REFERENCES parts(id)
);

DROP TRIGGER IF EXISTS trg_part_allocations_updated_at ON part_allocations;
CREATE TRIGGER trg_part_allocations_updated_at BEFORE UPDATE ON part_allocations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- INDEXES FOR OPTIMIZED QUERY PERFORMANCE
-- =====================================================
CREATE INDEX IF NOT EXISTS idx_vehicles_vin ON vehicles (vin);
CREATE INDEX IF NOT EXISTS idx_vehicles_customer ON vehicles (customer_id);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles (status);
CREATE INDEX IF NOT EXISTS idx_claims_status ON warranty_claims (status);
CREATE INDEX IF NOT EXISTS idx_claims_vehicle ON warranty_claims (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_claims_number ON warranty_claims (claim_number);
CREATE INDEX IF NOT EXISTS idx_parts_number ON parts (part_number);
CREATE INDEX IF NOT EXISTS idx_parts_category ON parts (category);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON service_campaigns (status);
CREATE INDEX IF NOT EXISTS idx_inventory_part ON inventory (part_id);
CREATE INDEX IF NOT EXISTS idx_inventory_center ON inventory (service_center);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON audit_logs (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_appointments_sc ON appointments (service_center);
CREATE INDEX IF NOT EXISTS idx_allocations_sc ON part_allocations (service_center);

-- =====================================================
-- SEED DATA - ROLES
-- =====================================================
INSERT INTO roles (name, description) VALUES 
('ADMIN', 'System Administrator with full access'),
('EVM_STAFF', 'EV Manufacturer Representative'),
('SC_STAFF', 'Service Center Operations Staff'),
('SC_TECHNICIAN', 'Service Center Maintenance Technician')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

-- =====================================================
-- SEED DATA - USERS
-- Default Password: password123 (BCrypt hash)
-- =====================================================
INSERT INTO users (username, password, full_name, email, phone, service_center, active) VALUES 
('admin', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'System Administrator', 'admin@evwarranty.com', '+84912345001', NULL, TRUE),
('evmstaff', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'Sarah Lee', 'sarah.lee@evmanufacturer.com', '+84912345004', NULL, TRUE),
('scstaff', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'Nguyen Van A', 'staff.hanoi@servicecenter.com', '+84912345002', 'SC-HANOI-01', TRUE),
('sctech', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'Tran Van B', 'tech.hanoi@servicecenter.com', '+84912345003', 'SC-HANOI-01', TRUE),
('scstaff2', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'Le Thi C', 'staff.hcm@servicecenter.com', '+84912345005', 'SC-HCMC-01', TRUE),
('sctech2', '$2a$10$eqBrtHhSJ4PhavV.ywEYG.AOhhnuzeg3d27.YHc.W4GTkUbA4b99G', 'Pham Van D', 'tech.hcm@servicecenter.com', '+84912345006', 'SC-HCMC-01', TRUE)
ON CONFLICT (username) DO UPDATE SET full_name = EXCLUDED.full_name, email = EXCLUDED.email;

-- Map User Roles
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'admin' AND r.name = 'ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'evmstaff' AND r.name = 'EVM_STAFF'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'scstaff' AND r.name = 'SC_STAFF'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'sctech' AND r.name = 'SC_TECHNICIAN'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'scstaff2' AND r.name = 'SC_STAFF'
ON CONFLICT (user_id, role_id) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r WHERE u.username = 'sctech2' AND r.name = 'SC_TECHNICIAN'
ON CONFLICT (user_id, role_id) DO NOTHING;

-- =====================================================
-- SEED DATA - CUSTOMERS
-- =====================================================
INSERT INTO customers (full_name, email, phone, address, city, state, zip_code, country, id_number, id_type) VALUES 
('Nguyen Van Minh', 'minh.nguyen@gmail.com', '+84903123456', '123 Le Loi Street, District 1', 'Ho Chi Minh City', 'HCMC', '700000', 'Vietnam', '079092001234', 'CITIZEN_ID'),
('Tran Thi Huong', 'huong.tran@yahoo.com', '+84918234567', '45 Nguyen Hue Boulevard', 'Hanoi', 'Hanoi', '100000', 'Vietnam', '001095005678', 'CITIZEN_ID'),
('Le Hoang Nam', 'nam.le@outlook.com', '+84922345678', '789 Tran Hung Dao St', 'Da Nang', 'Da Nang', '500000', 'Vietnam', '048088009012', 'CITIZEN_ID'),
('Pham Duc Anh', 'ducanh.pham@gmail.com', '+84933456789', '12 Vo Thi Sau Street', 'Can Tho', 'Can Tho', '900000', 'Vietnam', '092091003456', 'CITIZEN_ID'),
('Vu Hong Hanh', 'hanh.vu@hotmail.com', '+84944567890', '56 Hai Ba Trung St', 'Hai Phong', 'Hai Phong', '180000', 'Vietnam', '031093007890', 'CITIZEN_ID')
ON CONFLICT (email) DO UPDATE SET full_name = EXCLUDED.full_name;

-- =====================================================
-- SEED DATA - WARRANTY POLICIES
-- =====================================================
INSERT INTO warranty_policies (name, description, duration_months, mileage_limit, coverage_type, applicable_models, is_active) VALUES 
('Standard EV Bumper-to-Bumper', 'Basic warranty coverage for all vehicle components excluding wear and tear', 48, 50000, 'BUMPER_TO_BUMPER', 'VF8, VF9, Model 3, Model Y, Ioniq 5', TRUE),
('High-Voltage Battery & Drive Unit', 'Extended coverage for high-voltage battery pack and electric motor assembly', 96, 160000, 'BATTERY_AND_POWERTRAIN', 'VF8, VF9, Model 3, Model Y, Ioniq 5', TRUE),
('EV Extended Powertrain Protection', 'Optional extended drivetrain and power electronics warranty', 72, 120000, 'POWERTRAIN', 'All EV Models', TRUE)
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

-- =====================================================
-- SEED DATA - VEHICLES
-- =====================================================
INSERT INTO vehicles (vin, model, make, year, color, battery_type, battery_capacity, motor_type, mileage, manufacture_date, purchase_date, warranty_start_date, warranty_end_date, status, customer_id) VALUES 
('VF8E3400123456789', 'VF8 Plus', 'VinFast', 2023, 'Crimson Red', 'CATL Lithium-ion NMC', 87.7, 'Dual Motor AWD (300kW)', 45200, '2023-01-15', '2023-02-10', '2023-02-10', '2033-02-10', 'ACTIVE', 1),
('VF9P0000987654321', 'VF9 Eco', 'VinFast', 2023, 'Jet Black', 'CATL Lithium-ion NMC', 123.0, 'Dual Motor AWD (300kW)', 28500, '2023-03-20', '2023-04-15', '2023-04-15', '2033-04-15', 'ACTIVE', 2),
('5YJ3E1EA1NF123456', 'Model 3 Long Range', 'Tesla', 2022, 'Pearl White', 'Panasonic NCA', 82.0, 'Dual Motor AWD (324kW)', 68000, '2022-05-10', '2022-06-01', '2022-06-01', '2026-06-01', 'ACTIVE', 3),
('7SAYGDEF5PA654321', 'Model Y Performance', 'Tesla', 2023, 'Solid Black', 'LG Energy Solution', 78.1, 'Dual Motor Performance', 32000, '2023-02-01', '2023-03-12', '2023-03-12', '2027-03-12', 'ACTIVE', 4),
('KM8KR4AE3NU112233', 'Ioniq 5 AWD', 'Hyundai', 2023, 'Gravity Gold', 'SK Innovation NMC', 77.4, 'Dual Motor AWD (239kW)', 19400, '2023-06-10', '2023-07-01', '2023-07-01', '2028-07-01', 'ACTIVE', 5)
ON CONFLICT (vin) DO UPDATE SET model = EXCLUDED.model;

-- =====================================================
-- SEED DATA - PARTS CATALOG
-- =====================================================
INSERT INTO parts (part_number, name, description, category, price, warranty_months, manufacturer, model_compatibility, is_active, min_stock_level) VALUES 
('BAT-VF8-87K', 'VinFast 87.7kWh Battery Pack Assembly', 'High-voltage traction battery pack assembly with Integrated Liquid Cooling', 'BATTERY', 14500.00, 120, 'CATL / VinES', 'VF8 Plus, VF8 Eco', TRUE, 2),
('MTR-VF-300K', 'VF Dual Motor AWD Powertrain Unit', 'Front and rear electric motor drive unit assembly (300kW combined output)', 'POWERTRAIN', 7800.00, 96, 'Bosch / VinFast', 'VF8, VF9', TRUE, 2),
('BMS-HV-MODU', 'High-Voltage Battery Management System (BMS)', 'Central BMS ECU module monitoring cell voltages, temperature & state-of-charge', 'ELECTRONICS', 1350.00, 48, 'Continental', 'VF8, VF9, Model 3, Model Y', TRUE, 5),
('OBC-AC-11KW', '11kW Onboard AC Charger Module', 'Bi-directional onboard AC-to-DC charger unit', 'CHARGING', 1850.00, 48, 'Delta Electronics', 'Universal EV', TRUE, 4),
('INV-HV-200K', 'High-Voltage SiC Traction Inverter', 'Silicon Carbide power inverter module converting DC battery power to 3-phase AC', 'ELECTRONICS', 3200.00, 60, 'Denso', 'VF8, Model 3, Ioniq 5', TRUE, 3),
('HTP-EV-SYS', 'EV Heat Pump & Thermal Management Unit', 'Integrated heat pump compressor and coolant valve assembly', 'CLIMATE', 1600.00, 36, 'Hanon Systems', 'Universal EV', TRUE, 4),
('BRK-REG-PAD', 'Regenerative Brake Pad & Rotor Kit', 'Low-wear ceramic front brake pads and ventilated rotors for EV regen braking', 'BRAKES', 420.00, 24, 'Brembo', 'VF8, VF9, Model 3', TRUE, 8),
('DSP-INF-156', '15.6-inch HD Infotainment Screen Unit', 'Central touchscreen infotainment display assembly with integrated MCU', 'ELECTRONICS', 2100.00, 36, 'LG Display', 'VF8, VF9', TRUE, 3)
ON CONFLICT (part_number) DO UPDATE SET name = EXCLUDED.name;

-- =====================================================
-- SEED DATA - VEHICLE PARTS (INSTALLED)
-- =====================================================
INSERT INTO vehicle_parts (vehicle_id, part_id, serial_number, installation_date, warranty_start_date, warranty_end_date, status, notes) VALUES 
(1, 1, 'SN-BAT-VF8-2023-00912', '2023-01-15', '2023-02-10', '2033-02-10', 'INSTALLED', 'Factory original high-voltage battery pack'),
(1, 3, 'SN-BMS-2023-11029', '2023-01-15', '2023-02-10', '2027-02-10', 'INSTALLED', 'Factory original BMS module'),
(2, 1, 'SN-BAT-VF9-2023-00441', '2023-03-20', '2023-04-15', '2033-04-15', 'INSTALLED', 'Factory original 123kWh battery pack'),
(3, 5, 'SN-INV-TES-2022-88219', '2022-05-10', '2022-06-01', '2027-06-01', 'INSTALLED', 'Factory original SiC traction inverter')
ON CONFLICT DO NOTHING;

-- =====================================================
-- SEED DATA - SERVICE CAMPAIGNS & RECALLS
-- =====================================================
INSERT INTO service_campaigns (campaign_number, title, description, campaign_type, status, severity_level, affected_models, remedy_description, estimated_repair_time, total_affected, completed_count, start_date, end_date) VALUES 
('SC2024001', 'BMS Firmware & Battery Thermal Calibration Update', 'Software update to optimize thermal management during DC fast-charging and resolve false cell voltage alarms', 'SERVICE_BULLETIN', 'ACTIVE', 'MEDIUM', 'VF8 Plus (2023), Model 3 (2022-2023)', 'Reflash BMS software to v3.2.1 and recalibrate thermal sensor thresholds', 1.0, 1200, 485, '2024-01-15', '2024-12-31'),
('SC2024002', 'High-Voltage Traction Inverter O-Ring Seal Inspection', 'Safety recall to inspect and replace silicon sealing gaskets on high-voltage traction inverter housings to prevent moisture ingress', 'RECALL', 'ACTIVE', 'HIGH', 'VF8, VF9, Model Y (2023)', 'Inspect inverter housing seal; replace seal gasket and apply waterproof sealant', 2.5, 650, 192, '2024-02-01', '2024-11-30'),
('SC2024003', 'Front Suspension Lower Control Arm Torque Verification', 'Service advisory to verify bolt torque specification on front suspension lower control arm assemblies', 'SERVICE_BULLETIN', 'COMPLETED', 'LOW', 'VF8, Model 3 (2022-2023)', 'Inspect lower control arm bolts and retorque to 115 Nm specification', 0.5, 450, 450, '2023-09-01', '2024-03-01')
ON CONFLICT (campaign_number) DO UPDATE SET title = EXCLUDED.title;

-- =====================================================
-- SEED DATA - INVENTORY (SERVICE CENTER STOCK)
-- =====================================================
INSERT INTO inventory (part_id, service_center, quantity_on_hand, quantity_reserved, quantity_on_order, reorder_point, location) VALUES 
(1, 'SC-HANOI-01', 3, 1, 2, 2, 'Battery Bay A-01'),
(2, 'SC-HANOI-01', 2, 0, 1, 2, 'Powertrain Bay B-02'),
(3, 'SC-HANOI-01', 12, 2, 5, 5, 'Electronics Shelf E-04'),
(4, 'SC-HANOI-01', 8, 1, 0, 4, 'Charging Shelf C-01'),
(5, 'SC-HANOI-01', 4, 1, 2, 3, 'Electronics Shelf E-02'),
(6, 'SC-HANOI-01', 6, 0, 0, 3, 'Climate Rack D-01'),
(7, 'SC-HANOI-01', 20, 2, 10, 8, 'Brakes Rack R-01'),
(8, 'SC-HANOI-01', 5, 1, 0, 3, 'Electronics Shelf E-01'),
-- Stock for SC-HCMC-01
(1, 'SC-HCMC-01', 2, 0, 2, 2, 'Battery Bay A-02'),
(3, 'SC-HCMC-01', 10, 1, 5, 4, 'Electronics Shelf E-03'),
(5, 'SC-HCMC-01', 5, 0, 0, 3, 'Electronics Shelf E-05'),
(7, 'SC-HCMC-01', 15, 0, 10, 8, 'Brakes Rack R-02')
ON CONFLICT (part_id, service_center) DO UPDATE SET quantity_on_hand = EXCLUDED.quantity_on_hand;

-- =====================================================
-- SEED DATA - WARRANTY CLAIMS
-- =====================================================
INSERT INTO warranty_claims (claim_number, vehicle_id, vehicle_part_id, warranty_policy_id, failure_description, diagnosis_notes, repair_description, labor_hours, labor_cost, parts_cost, total_cost, status, mileage_at_claim, submitted_by, technician_id, reviewed_by, service_center, submitted_at, reviewed_at, completed_at) VALUES 
('CLM2024001', 1, 2, 2, 'Intermittent battery cell voltage imbalance warning displayed on instrument cluster during fast charging', 'Diagnostic DTC P0A80 detected. BMS slave module board sensor channel #4 reading outside tolerance', 'Replaced BMS controller board module and updated firmware to v3.2.1', 3.5, 175.00, 1350.00, 1525.00, 'COMPLETED', 44800, 3, 4, 2, 'SC-HANOI-01', '2024-02-10 09:30:00', '2024-02-10 14:00:00', '2024-02-11 16:30:00'),
('CLM2024002', 3, 4, 1, 'Traction inverter high-temperature warning during highway driving at elevated speed', 'Coolant passage flow sensor reporting restricted flow. Micro-fracture on inverter coolant seal O-ring', 'Pending replacement of SiC traction inverter assembly and coolant flush', 4.0, 200.00, 3200.00, 3400.00, 'APPROVED', 67500, 3, 4, 2, 'SC-HANOI-01', '2024-03-01 10:15:00', '2024-03-01 16:45:00', NULL),
('CLM2024003', 2, NULL, 1, 'Abnormal hum noise coming from front regenerative braking assembly under deceleration', 'Inspected front brake rotors and pads. Wear within normal maintenance operating limits; non-warranty item', 'Claim rejected - routine brake pad wear is excluded from standard warranty coverage', 1.0, 50.00, 0.00, 50.00, 'REJECTED', 28200, 5, 6, 2, 'SC-HCMC-01', '2024-03-05 11:00:00', '2024-03-05 15:20:00', NULL),
('CLM2024004', 4, NULL, 1, 'AC charging stops unexpectedly after 15 minutes of 11kW home charging', 'Diagnosing onboard AC charger control board interlock circuit', NULL, 0.0, 0.00, 0.00, 0.00, 'SUBMITTED', 31900, 5, NULL, NULL, 'SC-HCMC-01', '2024-03-10 08:45:00', NULL, NULL)
ON CONFLICT (claim_number) DO UPDATE SET failure_description = EXCLUDED.failure_description;

-- =====================================================
-- SEED DATA - APPOINTMENTS
-- =====================================================
INSERT INTO appointments (vehicle_id, campaign_id, appointment_date, status, service_center, notes) VALUES 
(1, 1, '2024-03-20 09:00:00', 'SCHEDULED', 'SC-HANOI-01', 'BMS Firmware Update & System Thermal Check'),
(2, 2, '2024-03-22 14:00:00', 'SCHEDULED', 'SC-HCMC-01', 'Recall SC2024002 Inverter Seal Inspection'),
(5, NULL, '2024-03-25 10:30:00', 'CONFIRMED', 'SC-DANANG-01', 'Annual Routine EV Battery Health Diagnostic')
ON CONFLICT DO NOTHING;

-- =====================================================
-- SEED DATA - PART ALLOCATIONS (SUPPLY CHAIN)
-- =====================================================
INSERT INTO part_allocations (part_id, service_center, quantity, status, tracking_number, requested_at, shipped_at, received_at) VALUES 
(1, 'SC-HANOI-01', 2, 'SHIPPED', 'TRK-VN-2024-9901', '2024-03-01 08:00:00', '2024-03-02 10:30:00', NULL),
(5, 'SC-HCMC-01', 3, 'DELIVERED', 'TRK-VN-2024-8842', '2024-02-20 09:15:00', '2024-02-21 11:00:00', '2024-02-23 15:45:00')
ON CONFLICT DO NOTHING;

-- =====================================================
-- SEED DATA - AUDIT LOGS
-- =====================================================
INSERT INTO audit_logs (username, action, resource_type, resource_id, details) VALUES 
('admin', 'SYSTEM_INITIALIZATION', 'SYSTEM', 1, 'Database schema and seed data loaded successfully'),
('scstaff', 'CREATE_CLAIM', 'CLAIM', 1, 'Submitted warranty claim CLM2024001 for vehicle VIN VF8E3400123456789'),
('evmstaff', 'APPROVE_CLAIM', 'CLAIM', 2, 'Approved warranty claim CLM2024002 with total estimated cost $3,400.00'),
('evmstaff', 'CREATE_CAMPAIGN', 'CAMPAIGN', 2, 'Published safety recall SC2024002 for Inverter O-Ring Seal Inspection');
