-- =====================================================
-- V4: Add Fleet Rental Columns to Vehicles & Platform Tables
-- =====================================================

-- 1. Extend Vehicles table with Fleet & Specs fields
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS brand VARCHAR(100) DEFAULT 'VinFast';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS model_name VARCHAR(100);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS car_type VARCHAR(30) DEFAULT 'SUV';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS license_plate VARCHAR(30);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS daily_price DECIMAL(10, 2) DEFAULT 120.00;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS transmission VARCHAR(50) DEFAULT 'Automatic';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS capacity VARCHAR(50) DEFAULT '5 seats';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS range_km INT DEFAULT 450;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS battery_fuel_percent INT DEFAULT 90;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS top_speed_kmh INT DEFAULT 200;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS acceleration_spec VARCHAR(50) DEFAULT '5.5s (0-100km/h)';
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS hero_image_url VARCHAR(255);
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS units_count INT DEFAULT 1;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS fleet_status VARCHAR(20) DEFAULT 'AVAILABLE';

-- 2. Client Profiles Table
CREATE TABLE IF NOT EXISTS client_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    residence_card_number VARCHAR(100),
    driver_license_number VARCHAR(100),
    address VARCHAR(255),
    points INT DEFAULT 0,
    total_spent DECIMAL(12, 2) DEFAULT 0.00,
    total_bookings INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. Driver Profiles Table
CREATE TABLE IF NOT EXISTS driver_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    assigned_vehicle_id BIGINT,
    status VARCHAR(30) DEFAULT 'ON_DUTY',
    experience_years INT DEFAULT 1,
    rating DECIMAL(3, 2) DEFAULT 5.00,
    performance_badge VARCHAR(50) DEFAULT 'Excellent',
    license_number VARCHAR(100),
    monthly_work_hours INT DEFAULT 160,
    avatar_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (assigned_vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL
);

-- 4. Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_code VARCHAR(50) UNIQUE NOT NULL,
    client_id BIGINT,
    vehicle_id BIGINT NOT NULL,
    driver_id BIGINT,
    rental_plan VARCHAR(30) DEFAULT 'DAILY',
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    payment_status VARCHAR(30) DEFAULT 'PAID',
    status VARCHAR(30) DEFAULT 'APPROVED',
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
    FOREIGN KEY (driver_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 5. Telemetry Logs Table
CREATE TABLE IF NOT EXISTS telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed_kmh DOUBLE PRECISION DEFAULT 0.0,
    heading DOUBLE PRECISION DEFAULT 0.0,
    battery_percent INT DEFAULT 90,
    motor_temperature DOUBLE PRECISION DEFAULT 38.0,
    engine_status VARCHAR(20) DEFAULT 'ON',
    status_text VARCHAR(50) DEFAULT 'In Transit',
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
);

-- 6. Charging Stations Table
CREATE TABLE IF NOT EXISTS charging_stations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    total_ports INT DEFAULT 8,
    available_ports INT DEFAULT 5,
    power_kw INT DEFAULT 150,
    status VARCHAR(30) DEFAULT 'OPERATIONAL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Invoices Table
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    booking_id BIGINT,
    client_id BIGINT,
    amount DECIMAL(12, 2) NOT NULL,
    due_date DATE,
    paid_date DATE,
    status VARCHAR(30) DEFAULT 'COMPLETED',
    payment_method VARCHAR(50) DEFAULT 'VNPAY',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL,
    FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE SET NULL
);

-- 8. Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    expense_date DATE NOT NULL,
    recipient_name VARCHAR(150),
    payment_method VARCHAR(50) DEFAULT 'BANK_TRANSFER',
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Conversations & Messages Table
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_one_id BIGINT NOT NULL,
    participant_two_id BIGINT NOT NULL,
    last_message TEXT,
    last_message_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (participant_one_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_two_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    attachment_urls TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 10. Pre-orders Table
CREATE TABLE IF NOT EXISTS pre_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    color VARCHAR(50),
    scooter_model VARCHAR(100) NOT NULL,
    content TEXT,
    status VARCHAR(30) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. Seed initial Charging Stations & Pre-orders
INSERT INTO charging_stations (name, address, latitude, longitude, total_ports, available_ports, power_kw, status) VALUES
('Trạm sạc V-GREEN Vincom Center Landmark 81', '720A Điện Biên Phủ, Phường 22, Bình Thạnh, TP.HCM', 10.795100, 106.721800, 12, 8, 250, 'OPERATIONAL'),
('Trạm sạc V-GREEN Vincom Mega Mall Thảo Điền', '159 Xa Lộ Hà Nội, Thảo Điền, TP. Thủ Đức, TP.HCM', 10.803200, 106.741500, 8, 5, 150, 'OPERATIONAL'),
('Trạm sạc V-GREEN Vincom Center Bà Triệu', '191 Bà Triệu, Lê Đại Hành, Hai Bà Trưng, Hà Nội', 21.011800, 105.849600, 10, 6, 250, 'OPERATIONAL'),
('Trạm sạc V-GREEN Vincom Royal City', '72A Nguyễn Trãi, Thượng Đình, Thanh Xuân, Hà Nội', 21.002800, 105.816400, 16, 11, 250, 'OPERATIONAL')
ON CONFLICT DO NOTHING;
